classdef test_routeB_smoothness_terms < matlab.unittest.TestCase
    methods (TestClassSetup)
        function addSourcePath(~)
            rootDir = fileparts(fileparts(mfilename("fullpath")));
            addpath(fullfile(rootDir, "src"));
        end
    end

    methods (Test)
        function smoothnessPenaltiesReduceStepVariation(testCase)
            cfg = HCDR_config_planar("n_m", 2, "n_c", 8);
            q = [0.02; -0.03; 0.08; cfg.q_home(:)];
            qd = zeros(size(q));
            provider = @(qIn, ~) deal(eye(numel(qIn), "double"), 0.02 * ones(numel(qIn), 1, "double"));
            xTarget = [0.25; 0.10; 0.0];

            step1 = simulate_routeB_step(q, qd, cfg, ...
                "pin_provider", provider, ...
                "dt", 0.02, ...
                "use_multi_level", true, ...
                "x_d", xTarget, ...
                "xd_d", zeros(3, 1), ...
                "xdd_d", zeros(3, 1), ...
                "collect_step_log", true);

            stepNoSmooth = simulate_routeB_step(step1.q_next, step1.qd_next, cfg, ...
                "pin_provider", provider, ...
                "dt", 0.02, ...
                "use_multi_level", true, ...
                "x_d", xTarget, ...
                "xd_d", zeros(3, 1), ...
                "xdd_d", zeros(3, 1), ...
                "prev_u_a_wo", step1.u_a_wo, ...
                "prev_qdd", step1.qdd, ...
                "smooth_weight_u", 0.0, ...
                "smooth_weight_qdd", 0.0, ...
                "collect_step_log", true);

            stepSmooth = simulate_routeB_step(step1.q_next, step1.qd_next, cfg, ...
                "pin_provider", provider, ...
                "dt", 0.02, ...
                "use_multi_level", true, ...
                "x_d", xTarget, ...
                "xd_d", zeros(3, 1), ...
                "xdd_d", zeros(3, 1), ...
                "prev_u_a_wo", step1.u_a_wo, ...
                "prev_qdd", step1.qdd, ...
                "smooth_weight_u", 5.0, ...
                "smooth_weight_qdd", 5.0, ...
                "collect_step_log", true);

            deltaNoSmooth = norm(stepNoSmooth.u_a_wo - step1.u_a_wo) + norm(stepNoSmooth.qdd - step1.qdd);
            deltaSmooth = norm(stepSmooth.u_a_wo - step1.u_a_wo) + norm(stepSmooth.qdd - step1.qdd);
            testCase.verifyLessThanOrEqual(deltaSmooth, deltaNoSmooth + 1e-9);
            testCase.verifyTrue(isfinite(stepSmooth.diagnostics.step_log.du_norm));
            testCase.verifyTrue(isfinite(stepSmooth.diagnostics.step_log.dqdd_norm));
        end
    end
end

