function onlineConfig = build_routeb_online_config_planar(cfg)
%BUILD_ROUTEB_ONLINE_CONFIG_PLANAR Pack MATLAB cfg into Python-online config.
%
%   ONLINECONFIG = BUILD_ROUTEB_ONLINE_CONFIG_PLANAR(CFG) returns a struct
%   with the sub-structs required by the v3.3 online split:
%   - model_kwargs: forwarded to Python Pinocchio term builders
%   - controller_cfg: planar geometry/bounds/weights for Python Route-B HQP
%   - runtime_cfg: IPC/process layout for controller/backend/viewer
%   - backend_cfg: MuJoCo backend loading + geometry setup
%   - viewer_cfg: visualization-only process options
%
%   This keeps the MATLAB and Python online-control branches aligned on one
%   geometry, tip-point, and safety-bound convention.

    arguments
        cfg (1, 1) struct
    end

    onlineConfig = struct();
    armCfg = struct();
    if isfield(cfg, "arm") && isstruct(cfg.arm)
        armCfg = cfg.arm;
    end
    repoRoot = fileparts(fileparts(mfilename("fullpath")));
    kortexRoot = fullfile(repoRoot, "kortex_description");
    urdfPath = char(resolve_string_field(armCfg, "urdf_path", ""));
    if strlength(string(urdfPath)) == 0
        urdfPath = fullfile(kortexRoot, "robots", "gen3_lite_gen3_lite_2f_local.urdf");
    end
    platformInertiaZ = (1.0 / 3.0) * double(cfg.platform.mass) * ...
        (double(cfg.platform.a)^2 + double(cfg.platform.a)^2);
    onlinePlatformXyBudget = min(double(max(0.1, cfg.frame.L - cfg.platform.a)), 0.25);
    onlinePlatformPsiBudget = min(pi, deg2rad(25.0));

    onlineConfig.model_kwargs = struct( ...
        "link_lengths", double(cfg.link_lengths(:)), ...
        "urdf_path", char(urdfPath), ...
        "platform_z0", double(cfg.z0), ...
        "root_mass_xy", double(cfg.platform.mass), ...
        "root_inertia_z", double(platformInertiaZ), ...
        "microgravity", true, ...
        "base_offset", double(resolve_vector3_field(armCfg, "offset_in_platform", [0.0; 0.0; 0.0])), ...
        "base_rotation", double(resolve_matrix3_field(armCfg, "base_rotation_in_platform", eye(3, "double"))), ...
        "gripper_joint_values", double(resolve_vector_field(armCfg, "gripper_joint_values", [])), ...
        "use_urdf", logical(resolve_logical_field(armCfg, "use_urdf_kinematics", false)), ...
        "tip_frame_name", "HCDR_TIP", ...
        "tip_left_body", char(resolve_string_field(armCfg, "urdf_left_tip_body", "LEFT_FINGER_DIST")), ...
        "tip_right_body", char(resolve_string_field(armCfg, "urdf_right_tip_body", "RIGHT_FINGER_DIST")), ...
        "tip_left_local", double(resolve_vector3_field(armCfg, "urdf_left_tip_local", [0.0; 0.0; 0.0])), ...
        "tip_right_local", double(resolve_vector3_field(armCfg, "urdf_right_tip_local", [0.0; 0.0; 0.0])), ...
        "tip_body", char(resolve_string_field(armCfg, "urdf_tip_body", "DUMMY")), ...
        "tip_local", double(resolve_vector3_field(armCfg, "urdf_tip_local", [0.0; 0.0; 0.0])));

    onlineConfig.controller_cfg = struct( ...
        "n_c", double(cfg.n_c), ...
        "n_m", double(cfg.n_m), ...
        "z0", double(cfg.z0), ...
        "cable_anchors_world", double(cfg.cable_anchors_world), ...
        "platform_attach_local", double(cfg.platform.r_attach), ...
        "T_min", double(cfg.T_min(:)), ...
        "T_max", double(cfg.T_max(:)), ...
        "tau_min", double(cfg.tau_min(:)), ...
        "tau_max", double(cfg.tau_max(:)), ...
        "T_safe_margin", double(expand_bound_local(cfg, "T_safe_margin", cfg.n_c, 0.0)), ...
        "T_center_offset", double(expand_bound_local(cfg, "T_center_offset", cfg.n_c, 0.0)), ...
        "f_ref", double(resolve_optional_reference(cfg, cfg.n_c)), ...
        "damped_pinv_lambda", double(cfg.damped_pinv_lambda), ...
        "weight_tension_ref", double(resolve_hqp_field(cfg, "weight_tension_ref", 0.0)), ...
        "fallback_prev_blend", 0.0, ...
        "fallback_platform_kp", double([15.0; 15.0; 8.0]), ...
        "fallback_platform_kd", double([6.0; 6.0; 3.0]), ...
        "smooth_weight_u", 0.05, ...
        "smooth_weight_qdd", 0.05, ...
        "control_mode", "cooperative", ...
        "qp_solver_backend", "osqp", ...
        "task_level_regularization", 1e-6, ...
        "platform_task_slack_weight", 1e4, ...
        "orientation_task_slack_weight", 1e4, ...
        "arm_task_slack_weight", 1e4, ...
        "tracking_task_slack_weight", 1e5, ...
        "alpha_T", 2.0, ...
        "tracking_alpha_T", 2.0, ...
        "near_goal_alpha_T", 8.0, ...
        "terminal_alpha_T", 10.0, ...
        "hold_alpha_T", 10.0, ...
        "beta_tau", 1e-3, ...
        "gamma_qdd", 1.0, ...
        "slack_weight", 1e4, ...
        "level1_lock_weight", 1e-2, ...
        "platform_xy_limit", double(onlinePlatformXyBudget), ...
        "platform_psi_limit", double(onlinePlatformPsiBudget), ...
        "platform_tracking_xy_limit", double(min(0.18, onlinePlatformXyBudget)), ...
        "platform_tracking_psi_limit", double(min(deg2rad(18.0), onlinePlatformPsiBudget)), ...
        "tracking_platform_tracking_xy_limit", double(min(0.18, onlinePlatformXyBudget)), ...
        "tracking_platform_tracking_psi_limit", double(min(deg2rad(18.0), onlinePlatformPsiBudget)), ...
        "near_goal_platform_tracking_xy_limit", double(min(0.12, onlinePlatformXyBudget)), ...
        "near_goal_platform_tracking_psi_limit", double(min(deg2rad(12.0), onlinePlatformPsiBudget)), ...
        "terminal_platform_tracking_xy_limit", double(min(0.08, onlinePlatformXyBudget)), ...
        "terminal_platform_tracking_psi_limit", double(min(deg2rad(8.0), onlinePlatformPsiBudget)), ...
        "hold_platform_tracking_xy_limit", double(min(0.06, onlinePlatformXyBudget)), ...
        "hold_platform_tracking_psi_limit", double(min(deg2rad(6.0), onlinePlatformPsiBudget)), ...
        "platform_limit_margin", 0.15, ...
        "platform_tracking_limit_margin", 0.04, ...
        "platform_limit_gain", 12.0, ...
        "platform_limit_velocity_gain", 3.0, ...
        "platform_state_guard_xy", 0.05, ...
        "platform_state_guard_psi", 0.10, ...
        "platform_tracking_state_guard_xy", 0.02, ...
        "platform_tracking_state_guard_psi", 0.05, ...
        "platform_velocity_limit", double([0.35; 0.35; 0.80]), ...
        "platform_recovery_qdd", double([3.0; 3.0; 2.0]), ...
        "platform_recovery_velocity_gain", 2.0, ...
        "platform_qdd_limit", double([15.0; 15.0; 12.0]), ...
        "arm_qdd_limit", double(12.0 * ones(cfg.n_m, 1, "double")), ...
        "arm_position_min", double(cfg.arm.joint_min(:)), ...
        "arm_position_max", double(cfg.arm.joint_max(:)), ...
        "arm_joint_limit_margin", double(0.20 * ones(cfg.n_m, 1, "double")), ...
        "arm_velocity_limit", double(2.0 * ones(cfg.n_m, 1, "double")), ...
        "task_accel_limit", double([2.5; 2.5; 2.0]), ...
        "near_goal_task_accel_limit", double([1.5; 1.5; 1.0]), ...
        "terminal_task_accel_limit", double([1.2; 1.2; 0.8]), ...
        "hold_task_accel_limit", double([0.4; 0.4; 0.3]), ...
        "platform_kp", double(resolve_hqp_field(cfg, "platform_kp", diag([12.0, 12.0, 16.0]))), ...
        "platform_kd", double(resolve_hqp_field(cfg, "platform_kd", diag([8.0, 8.0, 10.0]))), ...
        "platform_posture_weight", double(resolve_hqp_field(cfg, "platform_posture_weight", 1.0)), ...
        "ki", double(zeros(3, 3, "double")), ...
        "hold_ki", double(diag([6.0, 6.0, 4.0])), ...
        "hold_integral_limit", double([0.03; 0.03; 0.03]), ...
        "near_goal_position_tol", 0.05, ...
        "near_goal_platform_posture_weight", 10.0, ...
        "near_goal_arm_posture_weight", 0.0, ...
        "enable_arrival_hold", false, ...
        "terminal_reference_position_tol", 0.03, ...
        "terminal_reference_release_tol", 0.05, ...
        "terminal_reference_velocity_tol", 0.05, ...
        "terminal_reference_capture_duration_s", 0.08, ...
        "hold_position_tol", 0.02, ...
        "hold_velocity_tol", 0.05, ...
        "arrival_hold_position_tol", 0.015, ...
        "arrival_hold_release_tol", 0.040, ...
        "hold_stable_duration_s", 0.12, ...
        "hold_reference_velocity_tol", 1e-3, ...
        "hold_reference_acceleration_tol", 1e-2, ...
        "terminal_platform_posture_weight", 2.0, ...
        "terminal_arm_posture_weight", 0.0, ...
        "terminal_platform_task_slack_weight", 1e4, ...
        "terminal_add_arm_posture_task", false, ...
        "terminal_smooth_weight_u", 0.05, ...
        "terminal_smooth_weight_qdd", 0.05, ...
        "hold_platform_posture_weight", 30.0, ...
        "hold_arm_posture_weight", 1.5, ...
        "hold_smooth_weight_u", 1.0, ...
        "hold_smooth_weight_qdd", 4.0, ...
        "hold_weight_tension_ref", 0.0, ...
        "arm_posture_kp", 4.0, ...
        "arm_posture_kd", 2.0, ...
        "arm_posture_weight", 0.0, ...
        "cooperative_arm_posture_weight", 0.0, ...
        "cooperative_add_arm_posture_task", false, ...
        "platform_only_arm_posture_weight", 0.2, ...
        "arm_only_platform_posture_weight", 2.0, ...
        "cooperative_fix_orientation_only", false, ...
        "reference_speed_mps", 0.07, ...
        "min_move_duration_s", 0.8, ...
        "max_move_duration_s", 1.2, ...
        "settle_duration_s", 0.8);

    onlineConfig.runtime_cfg = struct( ...
        "backend_mode", "ipc_headless", ...
        "viewer_mode", "ipc_separate", ...
        "launch_backend", true, ...
        "launch_viewer", false, ...
        "transport", struct( ...
            "host", "127.0.0.1", ...
            "backend_port", 47051, ...
            "viewer_port", 47052, ...
            "timeout_s", 5.0, ...
            "poll_interval_s", 0.05));

    onlineConfig.backend_cfg = struct( ...
        "model_kind", "native_planar_hcdr", ...
        "repo_root", char(repoRoot), ...
        "kortex_root", char(kortexRoot), ...
        "urdf_path", char(urdfPath), ...
        "frame_L", double(cfg.frame.L), ...
        "frame_height", double(cfg.frame.height), ...
        "platform_z0", double(cfg.z0), ...
        "platform_a", double(cfg.platform.a), ...
        "platform_b", double(cfg.platform.b), ...
        "cable_d_pulley", double(cfg.cable.d_pulley), ...
        "base_offset_in_platform", double(resolve_vector3_field(armCfg, "offset_in_platform", [0.0; 0.0; 0.0])), ...
        "base_rotation_in_platform", double(resolve_matrix3_field(armCfg, "base_rotation_in_platform", eye(3, "double"))), ...
        "gripper_joint_values", double(resolve_vector_field(armCfg, "gripper_joint_values", [])), ...
        "tip_left_body", char(resolve_string_field(armCfg, "urdf_left_tip_body", "LEFT_FINGER_DIST")), ...
        "tip_right_body", char(resolve_string_field(armCfg, "urdf_right_tip_body", "RIGHT_FINGER_DIST")), ...
        "tip_left_local", double(resolve_vector3_field(armCfg, "urdf_left_tip_local", [0.0; 0.0; 0.0])), ...
        "tip_right_local", double(resolve_vector3_field(armCfg, "urdf_right_tip_local", [0.0; 0.0; 0.0])), ...
        "tip_body", char(resolve_string_field(armCfg, "urdf_tip_body", "DUMMY")), ...
        "tip_local", double(resolve_vector3_field(armCfg, "urdf_tip_local", [0.0; 0.0; 0.0])), ...
        "platform_mass", double(cfg.platform.mass), ...
        "platform_inertia_zz", double(platformInertiaZ), ...
        "platform_linear_damping_xy", 2.0, ...
        "platform_yaw_damping", 0.5, ...
        "platform_xy_limit", double(onlinePlatformXyBudget), ...
        "platform_psi_limit", double(onlinePlatformPsiBudget), ...
        "physics_mode", "native_mujoco_planar_hcdr", ...
        "microgravity", true, ...
        "default_dt", 0.02, ...
        "default_substeps", 10);
    onlineConfig.backend_cfg.gripper_joint_names = resolve_string_vector_field(armCfg, "gripper_joint_names", ...
        {"LEFT_BOTTOM", "LEFT_TIP", "RIGHT_BOTTOM", "RIGHT_TIP"});

    onlineConfig.viewer_cfg = struct( ...
        "enabled", false, ...
        "show_frame", true, ...
        "show_platform", true, ...
        "show_cables", true, ...
        "show_target", true, ...
        "bright_lighting", true, ...
        "camera_azimuth", 45.0, ...
        "camera_elevation", -22.0, ...
        "camera_distance", 4.2, ...
        "camera_lookat", double([0.0; 0.0; cfg.z0]));
end

function expanded = expand_bound_local(cfg, fieldName, expectedLength, defaultValue)
%EXPAND_BOUND_LOCAL Expand optional cfg field to expectedLength-by-1.
    if isfield(cfg, fieldName) && ~isempty(cfg.(fieldName))
        expanded = double(cfg.(fieldName)(:));
    else
        expanded = defaultValue * ones(expectedLength, 1, "double");
    end
    if numel(expanded) == 1
        expanded = repmat(expanded, expectedLength, 1);
    end
    if numel(expanded) ~= expectedLength
        error("HCDR:DimMismatch", "cfg.%s must be scalar or length %d.", fieldName, expectedLength);
    end
end

function reference = resolve_optional_reference(cfg, cableCount)
%RESOLVE_OPTIONAL_REFERENCE Return [] or n_c-by-1 cable preload reference.
    if isfield(cfg, "f_ref") && ~isempty(cfg.f_ref)
        reference = double(cfg.f_ref(:));
        if numel(reference) == 1
            reference = repmat(reference, cableCount, 1);
        end
        if numel(reference) ~= cableCount
            error("HCDR:DimMismatch", "cfg.f_ref must be scalar or length n_c.");
        end
    else
        reference = [];
    end
end

function value = resolve_hqp_field(cfg, fieldName, defaultValue)
%RESOLVE_HQP_FIELD Return cfg.hqp.<fieldName> or defaultValue.
    value = defaultValue;
    if isfield(cfg, "hqp") && isstruct(cfg.hqp) && isfield(cfg.hqp, fieldName)
        candidate = cfg.hqp.(fieldName);
        if ~isempty(candidate)
            value = candidate;
        end
    end
end

function value = resolve_string_field(cfgStruct, fieldName, defaultValue)
%RESOLVE_STRING_FIELD Return string field or default.
    value = string(defaultValue);
    if isfield(cfgStruct, fieldName) && ~isempty(cfgStruct.(fieldName))
        value = string(cfgStruct.(fieldName));
    end
end

function value = resolve_vector3_field(cfgStruct, fieldName, defaultValue)
%RESOLVE_VECTOR3_FIELD Return 3x1 vector field or default.
    value = double(defaultValue(:));
    if isfield(cfgStruct, fieldName) && numel(cfgStruct.(fieldName)) == 3
        value = double(cfgStruct.(fieldName)(:));
    end
end

function value = resolve_matrix3_field(cfgStruct, fieldName, defaultValue)
%RESOLVE_MATRIX3_FIELD Return 3x3 matrix field or default.
    value = double(defaultValue);
    if isfield(cfgStruct, fieldName) && isequal(size(cfgStruct.(fieldName)), [3, 3])
        value = double(cfgStruct.(fieldName));
    end
end

function value = resolve_vector_field(cfgStruct, fieldName, defaultValue)
%RESOLVE_VECTOR_FIELD Return column vector field or default.
    value = double(defaultValue(:));
    if isfield(cfgStruct, fieldName) && ~isempty(cfgStruct.(fieldName))
        value = double(cfgStruct.(fieldName)(:));
    end
end

function value = resolve_logical_field(cfgStruct, fieldName, defaultValue)
%RESOLVE_LOGICAL_FIELD Return logical field or default.
    value = logical(defaultValue);
    if isfield(cfgStruct, fieldName) && ~isempty(cfgStruct.(fieldName))
        value = logical(cfgStruct.(fieldName));
    end
end

function value = resolve_string_vector_field(cfgStruct, fieldName, defaultValue)
%RESOLVE_STRING_VECTOR_FIELD Return cellstr field or default string list.
    value = cellstr(string(defaultValue(:)));
    if isfield(cfgStruct, fieldName) && ~isempty(cfgStruct.(fieldName))
        value = cellstr(string(cfgStruct.(fieldName)(:)));
    end
end
